### ISSUE TITLE
Trouble getting regular Dotnet Client working

### ISSUE THREAD

**Issue by kaeedo** [Shmew/Fable.SignalR#21] opened 2021-03-22 13:06 UTC
Hello. I have successfully managed to get the Dotnet.Elmish client working as expected, but I can't seem to get the normal Dotnet client working. Invoking an action on the hub seems to work, but Sending an action doesn't. As far as I can tell, the request is successfully sent from the client, but the server never does anything with it.

Additionally, I can't seem to get Message Pack working either. The client always thinks that the server is using plain json serialization.

I've attached a minimal demo project for these problems. https://github.com/kaeedo/FableSignalRDotnetMinimal

I fear I'm missing some simple configuration, but since it works as expected when using the dotnet.elmish client, I thought I'd ask anyway.

Thanks.

**Comment by Shmew** [comment] 2021-03-23 14:48
Hey @kaeedo,

In order to receive send messages you need to use the `hub.OnMessage` method like this:

```fsharp
let hub =
    SignalR.Connect<SignalRHub.Action, _, _, SignalRHub.Response, _>(fun hub ->
        hub
            .WithUrl(sprintf "http://127.0.0.1:5000%s" Endpoints.Root)
            .ConfigureLogging(fun l -> l.SetMinimumLevel(LogLevel.Debug))
            .OnMessage(printfn "%A"))
```

As for MsgPack, are you making sure that both the client and server both have the setting enabled?

**Comment by kaeedo** [comment] 2021-03-23 20:50
But according to the docs (https://shmew.github.io/Fable.SignalR/#/dotnet-client) `You cannot define OnMessage at the declaration site of the hub, but rather at the points where you want to listen for a message.` This is also the case when I try to add the OnMessage in my code. My editor (Rider in this case) yells at me, and dotnet build fails with `The type 'HubConnectionBuilder<>' does not define the field, constructor or member 'OnMessage'.`

And I double checked that I have MsgPack enabled on both sides. Still the same problem.

**Comment by Shmew** [comment] 2021-03-23 21:22
Sorry I was still sleepy when I replied to this, yes you would do `hub.OnMessage(...)` after your `do! hub.Start()`. I don't see this in your repro, am I not seeing a current version?

Is MsgPack not working for you with both libraries or only the vanilla version? If so, I'll take a look at the repro and see what the issue is.

This might help, you can see the full test models I run against both JSON and MsgPack protocols [here](https://github.com/Shmew/Fable.SignalR/blob/master/tests/Fable.SignalR.DotNet.Tests/Generation.fs).

**Comment by kaeedo** [comment] 2021-03-23 21:49
Thanks for the help. The key missing piece in my client code was actually a `do! Async.Sleep(2000)`. I thought that doing `do! hub.Send <| SignalRHub.Action.OnConnect 1` would wait for the request to be completely sent before the program exits, but I guess not. I have now also added an OnMessage handler which works correctly.

However, I'm still facing MspPack issues :(
I remember one of the other issues mentioned a version mismatch. I'll continue to play with it.


Thanks

**Comment by kaeedo** [comment] 2021-03-24 14:20
Sorry to reopen this, but I just can't get the MsgPack version to work. I've updated my minimal reproduction demo ([Link again](https://github.com/kaeedo/FableSignalRDotnetMinimal/blob/main/FableDotnet.Client/Program.fs)).

If the client hub is configured with `UseMessagePack()` on [line 25](https://github.com/kaeedo/FableSignalRDotnetMinimal/blob/main/FableDotnet.Client/Program.fs#L25), and the server (now Saturn) also is configured with `use_messagepack` on [line 31 in Server](https://github.com/kaeedo/FableSignalRDotnetMinimal/blob/main/FableDotnet.Server/Program.fs), the client just hangs when it tries to send the first invoke, and the server seems to never receive the request.

Everything works just as expected when I comment out the `UseMessagePack` in the client and `use_messagepack` in the server.

I can confirm that running the tests in your repository works as well, so i'm just really confused at this point.


Thanks again

**Comment by Shmew** [comment] 2021-03-28 15:56
No worries, I'll check out your reproduction and see if I can figure out what's going on.

**Comment by kerams** [comment] 2021-04-01 08:49
The problem is this
https://github.com/kaeedo/FableSignalRDotnetMinimal/blob/9ab20274fa2a78044b1e27c8732ead6bcba5643c/FableDotnet.Client/Program.fs#L19-L21

Even though you are not using the stream API, serializers are being created for the message types, which are inferred as `obj` here. Since `obj` serializer is not a thing, you'll need to replace it with a dummy type.

```fsharp
let hub: HubConnection<SignalRHub.Action, unit, unit, SignalRHub.Response, unit> =
```

Now the client runs and exists, though the logging is a bit weird.

**Comment by kerams** [comment] 2021-04-01 08:58
I'd suggest checking if any of the user provided generic types are `obj` and if so, swap them for `unit` so that the whole thing does not blow up, and maybe print a warning (then it might be a good idea to have a connect overload without streaming support).

https://github.com/Shmew/Fable.SignalR/blob/2d9159ea1b093b5dc3624ee27edd37786ea747df/src/Fable.SignalR.Shared/MsgPack.fs#L25-L34

**Comment by kaeedo** [comment] 2021-04-01 12:36
Thank you so much. swapping out the `_`  for `unit` did the trick.

**Comment by Shmew** [comment] 2021-04-02 14:30
Awesome thanks for the help @kerams! I'll see what I can come up with to prevent this from occurring on my side of things (or at the very least a note about this in the docs). 

@kaeedo I think this has everything working as expected now, so I'm going to close this issue, but feel free to re-open if I'm mistaken.

**Closed by Shmew** 2021-04-02 14:30 UTC
